### ISSUE TITLE
Live Stats

### ISSUE THREAD

**Issue by montyanderson** [super3/embed.chat#3]
- [x] Messages
- [x] Unique Chatters
- [x] Websites
- [x] Pageviews
- [x] Chat Sessions
- [x] Live Chatters

**Comment by super3** [comment]
@montyanderson You did this already right?

**Comment by montyanderson** [comment]
@super3 Mostly, but it doesn't keep track of unique users.

**Comment by super3** [comment]
@montyanderson Changed it back to prod url and seeing this:
```undefined Unique Chatters
undefined Live Chatters
undefined Page Views```

**Comment by montyanderson** [comment]
@super3, think that's because we haven't updated/restarted the node server

**Comment by super3** [comment]
@montyanderson You are right. Fixed.
